### ISSUE TITLE
More explanation needed

### ISSUE THREAD

**Issue by Mekcyed** [Alyetama/label-studio-yolov5-backend#1]
Hi @Alyetama ,

could you explain which parameters are needed to be placed in the `.env` with `LABEL_STUDIO_BG_LABEL` and
how the `models_config.json` should look like?

Thanks!

**Comment by Alyetama** [comment]
`LABEL_STUDIO_BG_LABEL` is the label to apply when there is no detection in the image. Should defaults to `background`. I will add more documentation very soon and an explanation of `models_config.json`.

**Comment by Mekcyed** [comment]
Thanks a lot!
Stumbled across your repo at the weekend. Right at the moment i am also struggling to get it running without the connection to S3 (i want to label local images). But i am working on it :)

**Comment by Alyetama** [comment]
That should be an easy change. If you already worked on it, you can submit a PR, otherwise, you can open an issue for that and I will try to implement it soon.
